version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:lts

jobs:
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache
      - run: yarn install --immutable --immutable-cache --check-cache
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint

  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: yarn test:coverage

  prepack:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: yarn prepack

workflows:
  version: 2
  default:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - prepack:
          requires:
            - install
